// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnkOiRX7sWw7fyXmBkeWJnbHJytMgZ6k',
    appId: '1:1026444862110:web:dc1e995c677d591ccc918f',
    messagingSenderId: '1026444862110',
    projectId: 'cw06-87f74',
    authDomain: 'cw06-87f74.firebaseapp.com',
    storageBucket: 'cw06-87f74.firebasestorage.app',
    measurementId: 'G-6M84LXM930',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwupju7K_5mSEs5bVH7GvtvKXgcq_74o',
    appId: '1:1026444862110:android:84b4dfc9f11ae1cccc918f',
    messagingSenderId: '1026444862110',
    projectId: 'cw06-87f74',
    storageBucket: 'cw06-87f74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwABMPUDs7P13H5DGcnTN6c-PSzUhFw4',
    appId: '1:1026444862110:ios:af6889002eb821a0cc918f',
    messagingSenderId: '1026444862110',
    projectId: 'cw06-87f74',
    storageBucket: 'cw06-87f74.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwABMPUDs7P13H5DGcnTN6c-PSzUhFw4',
    appId: '1:1026444862110:ios:af6889002eb821a0cc918f',
    messagingSenderId: '1026444862110',
    projectId: 'cw06-87f74',
    storageBucket: 'cw06-87f74.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxnkOiRX7sWw7fyXmBkeWJnbHJytMgZ6k',
    appId: '1:1026444862110:web:ccb8968df08c7feccc918f',
    messagingSenderId: '1026444862110',
    projectId: 'cw06-87f74',
    authDomain: 'cw06-87f74.firebaseapp.com',
    storageBucket: 'cw06-87f74.firebasestorage.app',
    measurementId: 'G-GEWZTZD1ZJ',
  );
}
