// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwE38lTDOrouUE7T8aCI7vhNnWuJhbfOw',
    appId: '1:1034163021351:web:84a6b828d413ee989e9002',
    messagingSenderId: '1034163021351',
    projectId: 'activity-10-54e2a',
    authDomain: 'activity-10-54e2a.firebaseapp.com',
    storageBucket: 'activity-10-54e2a.appspot.com',
    measurementId: 'G-SHP1ZE3MLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqj_1iAIz8x74g3r_t6wEIaxCrOCdwqyI',
    appId: '1:1034163021351:android:b4ed11a192cf5c799e9002',
    messagingSenderId: '1034163021351',
    projectId: 'activity-10-54e2a',
    storageBucket: 'activity-10-54e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3sOyz_vKEJ0f_TUyppwqbhq2306OeUZA',
    appId: '1:1034163021351:ios:96a77e58d11bad3d9e9002',
    messagingSenderId: '1034163021351',
    projectId: 'activity-10-54e2a',
    storageBucket: 'activity-10-54e2a.appspot.com',
    iosBundleId: 'com.example.activity10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3sOyz_vKEJ0f_TUyppwqbhq2306OeUZA',
    appId: '1:1034163021351:ios:96a77e58d11bad3d9e9002',
    messagingSenderId: '1034163021351',
    projectId: 'activity-10-54e2a',
    storageBucket: 'activity-10-54e2a.appspot.com',
    iosBundleId: 'com.example.activity10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwE38lTDOrouUE7T8aCI7vhNnWuJhbfOw',
    appId: '1:1034163021351:web:a619fab363ef4e649e9002',
    messagingSenderId: '1034163021351',
    projectId: 'activity-10-54e2a',
    authDomain: 'activity-10-54e2a.firebaseapp.com',
    storageBucket: 'activity-10-54e2a.appspot.com',
    measurementId: 'G-5SWDMTD0NK',
  );
}
